  export const checkStatus = 'ตรวจสอบสถานะใบสมัคร' 
  export const applicationNo = 'ใบสมัครเลขที่'
  export const productName = 'ชื่อสินเชื่อ'
  export const productGroup = 'ประเภทสินเชื่อ'
  export const repayType = 'ประเภทการผ่อนชำระ'
  export const statusApplication = 'สถานะใบสมัคร'
  export const candidateName = 'ชื่อ-สกุล'
  export const creditLimit = 'วงเงินที่อนุมัต'
  export const getApplication = 'บริษัทได้รับใบสมัครเรียบร้อยแล้ว'
  export const checkApplication = 'อยู่ระหว่างการตรวจสอบข้อมูลและเอกสาร' 
  export const pendingApplication = 'อยู่ระหว่างพิจารณาสินเชื่อ'  
  export const approvedApplication = 'ได้รับการอนุมัติสินเชื่อเรียบร้อยแล้ว'
  export const cancelApplication = 'ใบสมัครถูกปฏิเสธ'
  export const phonenumber = 'เบอร์ติดต่อ'
  export const salesevice = 'Salesevice'
  export const SUBMIT = 'ยืนยัน'
  export const SEARCH = 'ค้นหา'
  export const DATACUSTOMER = 'ข้อมูลลูกค้า'
  export const SUMMARYDATA = 'สรุปยอด'
  export const APPLICATIONFORLEADER = 'ข้อมูลใบสมัคร'
  export const UNAUTHORIZED = 'Username หรือ Password ไม่ถูกต้อง'

  export const FIRSTNAME = 'ชื่อ'
  export const LASTNAME = 'นามสกุล'

  // sale ststus
  export const ALL = 'All'
  export const PENDING = 'Pending'
  export const REJECT = 'Reject'
  export const CANCEL = 'Cancel'
  export const APPROVE = 'Approve'
  export const INCOMPLETE = 'Incomplete' 