  export const checkStatus = 'ตรวจสอบสถานะใบสมัคร' 
  export const applicationNo = 'ใบสมัครเลขที่'
  export const productName = 'ชื่อสินเชื่อ'
  export const productGroup = 'ประเภทสินเชื่อ'
  export const repayType = 'ประเภทการผ่อนชำระ'
  export const statusApplication = 'สถานะใบสมัคร'
  export const candidateName = 'ชื่อ-สกุล'
  export const creditLimit = 'วงเงินที่อนุมัต'
  export const getApplication = 'บริษัทได้รับใบสมัครเรียบร้อยแล้ว'
  export const checkApplication = 'อยู่ระหว่างการตรวจสอบข้อมูลและเอกสาร' 
  export const pendingApplication = 'อยู่ระหว่างพิจารณาสินเชื่อ'  
  export const approvedApplication = 'ได้รับการอนุมัติสินเชื่อเรียบร้อยแล้ว'
  export const phonenumber = 'เบอร์ติดต่อ'
  export const salesevice = 'SALESERVICE'

  export const FIRSTNAME = 'ชื่อ'
  export const LASTNAME = 'นามสกุล'

  // Application status
  export const ALL = 'ทั้งหมด'
  export const FILLFORM = 'กรอกใบสมัคร'
  export const WAIT_VERIFY = 'ตรวจหลักฐาน'
  export const WAIT_ANALYST = 'วิเคราะห์สินเชื่อ'
  export const WAIT_APPROVE = 'รออนุมัติ'
  export const REJECT_STATUS = 'ปฏิเสธสินเชื่อ'
  export const WAIT_CONFIRM = 'รอยืนยันวงเงิน'
  export const WAIT_TRANSFER = 'รอโอนเงิน'
  export const TRANSFERRED = 'โอนเงินแล้ว'
